# Generated by Django 2.2.6 on 2019-10-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SugarLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('sugarlevel', models.PositiveSmallIntegerField()),
                ('warning', models.CharField(max_length=100)),
                ('trend', models.CharField(max_length=50)),
            ],
        ),
    ]
