# Generated by Django 2.2.6 on 2019-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0002_sugarlevel_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugarlevel',
            options={'get_latest_by': 'date'},
        ),
        migrations.RemoveField(
            model_name='sugarlevel',
            name='date',
        ),
        migrations.AlterField(
            model_name='sugarlevel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
