# Generated by Django 2.2.6 on 2019-11-14 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('jednostka', models.CharField(choices=[('kcal', 'kcal'), ('g', 'g')], max_length=15)),
                ('poziom_cukru', models.PositiveSmallIntegerField()),
                ('weglowodany', models.PositiveSmallIntegerField()),
                ('bialka', models.PositiveSmallIntegerField()),
                ('tluszcze', models.PositiveSmallIntegerField()),
                ('kalorycznosc', models.PositiveSmallIntegerField()),
                ('insulin_dose', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bolus', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
    ]
