# Generated by Django 2.2.6 on 2019-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_auto_20191122_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='warning',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
